[package]
name = "doom"
version = "0.1.0"
authors = ["Mark Glenn <mark.glenn@mbx.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
bitflags = "1.2.1"
num-traits = "0.2"
num-derive = "0.3"